version: '3'
services:
  webapp:
    build: .
    restart: always
    ports:
      - "9514:9514"
    environment:
      - sapic_host=0.0.0.0
      - sapic_redis_url=redis://@redis:6379
    volumes:
      - static:/picbed/static/
      - /data/picbed/:/picbed/static/upload/
    depends_on:
      - "redis"
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  static: