name: ci

on: [push, pull_request]

env:
  picbed_redis_url: "redis://localhost"

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        flask-version: ["1.0", "1.1.0"]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codecov Flask==${{ matrix.flask-version }}
        pip install -r requirements/all.txt

    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: 4
  
    - name: Test & upload report to coverage
      run: |
        cd src && coverage run -m unittest discover -p "test_*.py" && codecov -t ${{ secrets.CODECOV_TOKEN }}
